<?php
namespace app\controllers;

//发送模版消息
class TestPushMessageController extends WxController{

    public function beforeAction($action)
    {
        $this->checkOpenid();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    //发送模版消息
    public function actionPushMessage(){
        //获取token
        $token = WxController::getAccessToken();
        //设置url
        $url = 'https://api.weixin.qq.com/cgi-bin/message/template/send?access_token='.$token;
//        //设置时间
//        $sj = date('Y-m-d H:i:s',time());
//        //设置充值链接
//        $cz_url = 'http://www.peita.net';
//        //设置账户余额
//        $ye = '10元';
//        //设置账户名称
//        $name = '小郭';

        //设置发送的消息
        $message = [
            'touser'=>\Yii::$app->session->get('openid'),
            'template_id'=>'ZnUIqPEbw5BSpdd8NHB9Sj53_fIu8KCuTwln0jEtfEg',
            'url'=>$url,
            'data'=>[
                'first'=>['value'=>'发送模版消息测试','color'=>'#173177'],
                'keyword1'=>['value'=>'测试1','color'=>'#173177'],
                'keyword2'=>['value'=>'测试2','color'=>'#173177'],
                'keyword3'=>['value'=>'测试3','color'=>'#173177'],
                'keyword4'=>['value'=>'测试4','color'=>'#173177'],
                'keyword5'=>['value'=>'测试5','color'=>'#173177'],
                'remark'=>['value'=>'如有任何疑问请登录会员系统联系在线客服','color'=>'#173177']
            ]
        ];

        $data = json_encode($message);

        //发送
        $res = self::actionCurlRequest($url,$data);
        return $res;

    }


    //curl请求，支持post和get
    public function actionCurlRequest($url,$data=null){
        $curl = curl_init();
        curl_setopt($curl,CURLOPT_URL,$url);
        curl_setopt($curl,CURLOPT_SSL_VERIFYPEER,FALSE);
        curl_setopt($curl,CURLOPT_SSL_VERIFYHOST,FALSE);
        if(!empty($data)){
            curl_setopt($curl,CURLOPT_POST,1);
            curl_setopt($curl,CURLOPT_POSTFIELDS,$data);
        }

        curl_setopt($curl,CURLOPT_RETURNTRANSFER,1);
        $output = curl_exec($curl);
        curl_close($curl);
        return $output;
    }

    //是否关注公众号
    public function actionIsFollow(){
        $access_token = WxController::getAccessToken();
        $subscribe_msg = 'https://api.weixin.qq.com/cgi-bin/user/info?access_token='.$access_token.'&openid='.\Yii::$app->session->get('openid');
        $subscribe = json_decode(file_get_contents($subscribe_msg));
        $zyxx = $subscribe ->subscribe;
        var_dump($subscribe);exit;
        if ($zyxx !== 1) {
            echo'未关注！';
        }else{
            echo'已关注！';
        }
    }


}
